name: Terraform Destroy

variables:
 - group: terraform-workshop-variables
  
# Only run against develop
trigger: none

pool: 
  vmImage: 'ubuntu-latest'

stages :
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: Bash@3
        displayName: Terraform Init
        env:            
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
         ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)              
         ARM_TENANT_ID: $(ARM_TENANT_ID)
         ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/cfg/'  
          targetType: 'inline'
          script: |
            terraform init \
            -backend-config="resource_group_name=labfridtjof-terraform-test" \
            -backend-config="storage_account_name=labfridtjoftfstateua80pj" \
            -backend-config="container_name=p-terra" \
            -backend-config="key=terraform.tfstate"
  
      - task: Bash@3
        displayName: Terraform Destroy
        env:            
         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
         ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)              
         ARM_TENANT_ID: $(ARM_TENANT_ID) 
         ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)       
        inputs:
          workingDirectory: '$(System.DefaultWorkingDirectory)/cfg/'
          targetType: 'inline'
          script: |
            terraform destroy -auto-approve